Repository Juansero29/SFDScripts, pull requests merged in 2021-03, with the labels that each got.

#32 Airstrike cost
  SFDScripts/Internal/Hardcore/Hardcore.cs
Labels: enhancement

#33 Flashbang bleeding fix
  SFDScripts/Internal/Hardcore/Hardcore.cs
Labels: bug

#43 Flashbang duration
  SFDScripts/Internal/Hardcore/Hardcore.cs
Labels: enhancement

#51 Deploying new maps to server with GitHubAction
  .github/workflows/dotnet-desktop.yml
  SFDScripts/Internal/Hardcore/Hardcore.cs
  SFDScripts/Internal/Hardcore/Maps/Hardcore Classic Remastered.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Classic.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Cold War.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Deep Cliff.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Police Station.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Small Hill.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Summit Of Evil.sfdm
  SFDScripts/Internal/Hardcore/Maps/Hardcore Template.sfdm
Labels: enhancement

#52 41 flashbang not stunning players properly fixed
  SFDScripts/Internal/Hardcore/Hardcore.cs
Labels: bug, enhancement
